### ISSUE TITLE
Build Permission Denied

### ISSUE THREAD

**Issue by redknight1056** [sat8/tinkerboard-yocto-qt5-eglfs#1]
Hello @sat8, I really do hate to be the guy with all the problems but when I try and use the ". ./setup-environment" I get the following error:

`ben@debian:~/tinkerboard-yocto-qt5-eglfs-master$ . ./setup-environment
WARNING: <build-dir> undefined, use build as default dir
WARNING: <machine> undefined, use evb-rk3288 as default machine
bash: /home/ben/tinkerboard-yocto-qt5-eglfs-master/sources/poky/scripts/oe-setup-builddir: Permission denied
`
I have tried using "$sudo . ./setup-environment" but I get "sudo: .: command not found"
Is there something I've possibly missed?

**Comment by spedagadi** [comment]
@redknight1056 I think this was a mistake at my end. I have now committed the correct files. can you try now and check if the error is fixed. 
I recommend a fresh pull

     git clone https://github.com/sat8/tinkerboard-yocto-qt5-eglfs.git tinkerboard_yocto_qt5

**Comment by redknight1056** [comment]
Amazing, the build is going good so far.

**Comment by redknight1056** [comment]
Hmm it seems that the build has failed around the 3387 of 4851. When building qtwebkit.

I believe this issue is one you haven't caused but I have created an 'issue' on the rockchip github.

Just to ask the question did you manage to build the tool-chain?

Kind regards
